apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: gamedb
spec:
  selector:
    app: redis
  ports:
    - name: redis-service
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
