apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gamedb
  name: mongo-volume-claim
spec:
  resources:
    requests:
      storage: 1.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
