apiVersion: v1
kind: Service
metadata:
  namespace: gamedb
  name: mongo-svc
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-svc
      protcol: TCP
      port: 27017
      targetPort: 27017
