# Stage 1: Install dependencies
FROM node:18-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install --production --legacy-peer-deps && npm cache clean --force

# Stage 2: Build the application
FROM node:18-slim AS build
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build

# Stage 3: Create production image
FROM node:18-alpine AS production
WORKDIR /app
ENV NODE_ENV=production

# Copy only necessary files from the build stage
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

# Add a non-root user for better security
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

EXPOSE 3000

# Environment variable for the API base URL
ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:3636/api

CMD ["node", "server.js"]
